BEGIN TRANSACTION;

CREATE TABLE [activity] (
[id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[name] VARCHAR(256)  NOT NULL,
[beginDate] TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
[endDate] TIMESTAMP DEFAULT 'NULL' NULL,
[duration] INTEGER DEFAULT '0' NULL
);

CREATE TABLE [category] (
[id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[name] VARCHAR(80)  UNIQUE NOT NULL,
[description] VARCHAR(256)  NULL
);

CREATE TABLE [provider] (
[id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[userID] INTEGER  NOT NULL,
[is_available] BOOLEAN DEFAULT 'true' NOT NULL,
FOREIGN KEY(userID) REFERENCES user(id)
);

CREATE TABLE [seeker] (
[id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[userID] INTEGER  NOT NULL,
FOREIGN KEY(userID) REFERENCES user(id)
);

CREATE TABLE [skill] (
[id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[categoryID] INTEGER  NOT NULL,
[name] VARCHAR(80)  NOT NULL,
[description] VARCHAR(256)  NULL,
FOREIGN KEY(categoryID) REFERENCES category(id)
);

CREATE TABLE [user] (
[id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[username] VARCHAR(80)  NULL,
[email] VARCHAR(120)  NULL,
[pwd_hash] VARCHAR(120)  NULL,
[is_admin] BOOLEAN DEFAULT 'false' NULL
);

CREATE INDEX [IDX_CATEGORY_NAME] ON [category](
[name]  DESC
);

CREATE INDEX [IDX_CATEGORY_ID] ON [category](
[id]  DESC
);

COMMIT;
